"""Multipath fading channel simulator.

This module generates flat-fading equivalent complex channel coefficients by
summing multiple propagation paths.

A simplified multipath channel is modeled as:

    h = sum_{l=1}^{L} alpha_l

where each path gain is:

    alpha_l = a_l * exp(j * phi_l)

For machine learning models, the complex channel is represented as:

    x = [Re(h), Im(h)]

with shape:

    (num_samples, 2)
"""

from __future__ import annotations

import numpy as np


def exponential_power_profile(
    num_paths: int,
    decay_factor: float = 1.0,
    normalize: bool = True,
) -> np.ndarray:
    """Create an exponential multipath power profile.

    The path power profile is defined as:

        P_l = exp(-l / decay_factor)

    for l = 0, 1, ..., num_paths - 1.

    Args:
        num_paths:
            Number of multipath components.
        decay_factor:
            Controls how quickly path powers decay. Smaller values produce
            faster decay. Must be positive.
        normalize:
            If True, normalize powers so that their sum equals one.

    Returns:
        Array of path powers with shape (num_paths,).

    Raises:
        ValueError:
            If num_paths or decay_factor is invalid.
    """
    if num_paths <= 0:
        raise ValueError("num_paths must be a positive integer.")

    if decay_factor <= 0:
        raise ValueError("decay_factor must be positive.")

    path_indices = np.arange(num_paths, dtype=np.float64)
    powers = np.exp(-path_indices / decay_factor)

    if normalize:
        powers = powers / np.sum(powers)

    return powers.astype(np.float32)


def generate_multipath_samples(
    num_samples: int,
    num_paths: int = 5,
    decay_factor: float = 1.0,
    los_component: complex | None = None,
    normalize_power: bool = True,
    seed: int | None = None,
    return_complex: bool = False,
) -> np.ndarray:
    """Generate flat-fading multipath channel samples.

    Each sample is generated by summing multiple random-phase paths:

        h = sum_l a_l * exp(j * phi_l)

    where:

        a_l = sqrt(P_l)

    and:

        phi_l ~ Uniform(0, 2*pi)

    An optional deterministic line-of-sight component can be added:

        h_total = h + h_los

    Args:
        num_samples:
            Number of independent channel samples to generate.
        num_paths:
            Number of multipath components.
        decay_factor:
            Exponential path power decay factor. Smaller values mean that
            later paths become weaker more quickly.
        los_component:
            Optional deterministic complex line-of-sight component.
            Example: 1.0 + 0.0j.
        normalize_power:
            If True, normalize the generated channel samples so that the
            empirical average power E[|h|^2] is approximately one.
        seed:
            Optional random seed for reproducibility.
        return_complex:
            If True, return a complex-valued NumPy array with shape
            (num_samples,). If False, return a real-valued NumPy array with
            shape (num_samples, 2).

    Returns:
        Generated multipath fading samples.

        If return_complex is False:
            Array with shape (num_samples, 2), where column 0 is Re(h)
            and column 1 is Im(h).

        If return_complex is True:
            Complex-valued array with shape (num_samples,).

    Raises:
        ValueError:
            If num_samples, num_paths, or decay_factor is invalid.
    """
    if num_samples <= 0:
        raise ValueError("num_samples must be a positive integer.")

    if num_paths <= 0:
        raise ValueError("num_paths must be a positive integer.")

    if decay_factor <= 0:
        raise ValueError("decay_factor must be positive.")

    rng = np.random.default_rng(seed)

    path_powers = exponential_power_profile(
        num_paths=num_paths,
        decay_factor=decay_factor,
        normalize=True,
    )

    path_amplitudes = np.sqrt(path_powers)

    phases = rng.uniform(
        low=0.0,
        high=2.0 * np.pi,
        size=(num_samples, num_paths),
    )

    complex_paths = path_amplitudes[None, :] * np.exp(1j * phases)

    h = np.sum(complex_paths, axis=1)

    if los_component is not None:
        h = h + los_component

    if normalize_power:
        empirical_power = np.mean(np.abs(h) ** 2)

        if empirical_power <= 0:
            raise ValueError("Cannot normalize channel with zero power.")

        h = h / np.sqrt(empirical_power)

    if return_complex:
        return h

    samples = np.stack([h.real, h.imag], axis=1)

    return samples.astype(np.float32)


def multipath_magnitude(samples: np.ndarray) -> np.ndarray:
    """Compute magnitudes of multipath channel samples.

    Args:
        samples:
            Either a complex-valued array with shape (num_samples,) or a
            real-valued array with shape (num_samples, 2).

    Returns:
        Magnitudes with shape (num_samples,).

    Raises:
        ValueError:
            If the real-valued input shape is invalid.
    """
    if np.iscomplexobj(samples):
        return np.abs(samples)

    if samples.ndim != 2 or samples.shape[1] != 2:
        raise ValueError(
            "Real-valued samples must have shape (num_samples, 2)."
        )

    return np.sqrt(samples[:, 0] ** 2 + samples[:, 1] ** 2)


def average_channel_power(samples: np.ndarray) -> float:
    """Compute the average channel power E[|h|^2].

    Args:
        samples:
            Either a complex-valued array with shape (num_samples,) or a
            real-valued array with shape (num_samples, 2).

    Returns:
        Estimated average channel power.
    """
    magnitudes = multipath_magnitude(samples)
    power = np.mean(magnitudes**2)

    return float(power)