"""Aggregate RealNVP experiment metrics.

This script reads metrics JSON files generated by:

    scripts/train_realnvp_channel.py

and produces:

    results/reports/realnvp_channel_metrics_summary.md
    results/reports/realnvp_channel_metrics_summary.csv

Run from the repository root:

    python3 scripts/aggregate_realnvp_metrics.py
"""

from __future__ import annotations

import argparse
import csv
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ExperimentSummary:
    """Compact summary of one RealNVP experiment."""

    experiment_name: str
    channel_type: str
    test_nll: float
    best_val_nll: float
    final_train_nll: float
    final_val_nll: float
    reference_power: float
    generated_power: float
    reference_mean_real: float
    reference_mean_imag: float
    generated_mean_real: float
    generated_mean_imag: float
    reference_std_real: float
    reference_std_imag: float
    generated_std_real: float
    generated_std_imag: float


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Aggregate RealNVP metrics JSON files."
    )

    parser.add_argument(
        "--metrics-dir",
        type=Path,
        default=Path("results/metrics"),
        help="Directory containing metrics JSON files.",
    )

    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/reports"),
        help="Directory where summary files will be written.",
    )

    parser.add_argument(
        "--pattern",
        type=str,
        default="realnvp_*_metrics.json",
        help="Glob pattern for metrics files.",
    )

    return parser.parse_args()


def load_json(path: Path) -> dict[str, Any]:
    """Load one JSON file.

    Args:
        path:
            JSON file path.

    Returns:
        Parsed JSON dictionary.
    """
    with path.open("r", encoding="utf-8") as file:
        data = json.load(file)

    if not isinstance(data, dict):
        raise ValueError(f"Expected dictionary in JSON file: {path}")

    return data


def extract_summary(metrics: dict[str, Any]) -> ExperimentSummary:
    """Extract compact metrics from one experiment dictionary.

    Args:
        metrics:
            Metrics dictionary produced by the experiment script.

    Returns:
        ExperimentSummary instance.
    """
    experiment = metrics["experiment"]
    channel = metrics["channel"]
    training = metrics["training"]
    test_likelihood = metrics["test_likelihood"]
    reference_stats = metrics["reference_statistics"]
    generated_stats = metrics["generated_statistics"]

    return ExperimentSummary(
        experiment_name=str(experiment["name"]),
        channel_type=str(channel["type"]),
        test_nll=float(test_likelihood["mean_negative_log_likelihood"]),
        best_val_nll=float(training["best_val_loss"]),
        final_train_nll=float(training["final_train_loss"]),
        final_val_nll=float(training["final_val_loss"]),
        reference_power=float(reference_stats["average_power"]),
        generated_power=float(generated_stats["average_power"]),
        reference_mean_real=float(reference_stats["mean_real"]),
        reference_mean_imag=float(reference_stats["mean_imag"]),
        generated_mean_real=float(generated_stats["mean_real"]),
        generated_mean_imag=float(generated_stats["mean_imag"]),
        reference_std_real=float(reference_stats["std_real"]),
        reference_std_imag=float(reference_stats["std_imag"]),
        generated_std_real=float(generated_stats["std_real"]),
        generated_std_imag=float(generated_stats["std_imag"]),
    )


def format_float(value: float, digits: int = 4) -> str:
    """Format floating-point values for reports.

    Args:
        value:
            Number to format.
        digits:
            Number of decimal places.

    Returns:
        Formatted string.
    """
    return f"{value:.{digits}f}"


def summaries_to_markdown(summaries: list[ExperimentSummary]) -> str:
    """Convert experiment summaries to a GitHub-compatible Markdown report.

    Args:
        summaries:
            List of experiment summaries.

    Returns:
        Markdown text.
    """
    lines: list[str] = [
        "# RealNVP Channel Metrics Summary",
        "",
        "This file was generated from experiment metrics JSON files.",
        "",
        "## Main Comparison",
        "",
        "| Experiment | Channel | Test NLL | Best Val NLL | Ref Power | Gen Power |",
        "|---|---|---:|---:|---:|---:|",
    ]

    for summary in summaries:
        lines.append(
            "| "
            f"{summary.experiment_name} | "
            f"{summary.channel_type} | "
            f"{format_float(summary.test_nll)} | "
            f"{format_float(summary.best_val_nll)} | "
            f"{format_float(summary.reference_power)} | "
            f"{format_float(summary.generated_power)} |"
        )

    lines.extend(
        [
            "",
            "## Detailed Statistics",
            "",
            "| Experiment | Ref Mean | Gen Mean | Ref Std | Gen Std |",
            "|---|---:|---:|---:|---:|",
        ]
    )

    for summary in summaries:
        ref_mean = (
            f"({format_float(summary.reference_mean_real)}, "
            f"{format_float(summary.reference_mean_imag)})"
        )
        gen_mean = (
            f"({format_float(summary.generated_mean_real)}, "
            f"{format_float(summary.generated_mean_imag)})"
        )
        ref_std = (
            f"({format_float(summary.reference_std_real)}, "
            f"{format_float(summary.reference_std_imag)})"
        )
        gen_std = (
            f"({format_float(summary.generated_std_real)}, "
            f"{format_float(summary.generated_std_imag)})"
        )

        lines.append(
            "| "
            f"{summary.experiment_name} | "
            f"{ref_mean} | "
            f"{gen_mean} | "
            f"{ref_std} | "
            f"{gen_std} |"
        )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- Test NLL is the mean negative log-likelihood on the test split.",
            "- Ref Power is the empirical average power of simulated channel samples.",
            "- Gen Power is the empirical average power of RealNVP-generated samples.",
            "- Ref Mean and Gen Mean are reported as `(real, imaginary)`.",
            "- Ref Std and Gen Std are reported as `(real, imaginary)`.",
            "",
        ]
    )

    return "\n".join(lines)


def write_csv(summaries: list[ExperimentSummary], path: Path) -> None:
    """Write experiment summaries to CSV.

    Args:
        summaries:
            List of experiment summaries.
        path:
            Output CSV path.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = list(ExperimentSummary.__dataclass_fields__.keys())

    with path.open("w", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=fieldnames)
        writer.writeheader()

        for summary in summaries:
            writer.writerow(
                {
                    field: getattr(summary, field)
                    for field in fieldnames
                }
            )


def write_markdown(markdown_text: str, path: Path) -> None:
    """Write Markdown text to file.

    Args:
        markdown_text:
            Markdown content.
        path:
            Output path.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as file:
        file.write(markdown_text)


def find_metric_files(metrics_dir: Path, pattern: str) -> list[Path]:
    """Find metrics files.

    Args:
        metrics_dir:
            Directory containing metric files.
        pattern:
            Glob pattern.

    Returns:
        Sorted list of matching paths.

    Raises:
        FileNotFoundError:
            If the metrics directory does not exist or no files match.
    """
    if not metrics_dir.exists():
        raise FileNotFoundError(f"Metrics directory does not exist: {metrics_dir}")

    metric_files = sorted(metrics_dir.glob(pattern))

    if not metric_files:
        raise FileNotFoundError(
            f"No metric files found in {metrics_dir} using pattern {pattern}"
        )

    return metric_files


def main() -> None:
    """Aggregate metrics and write summary files."""
    args = parse_args()

    metric_files = find_metric_files(
        metrics_dir=args.metrics_dir,
        pattern=args.pattern,
    )

    summaries = [
        extract_summary(load_json(metric_file))
        for metric_file in metric_files
    ]

    markdown_text = summaries_to_markdown(summaries)

    markdown_path = args.output_dir / "realnvp_channel_metrics_summary.md"
    csv_path = args.output_dir / "realnvp_channel_metrics_summary.csv"

    write_markdown(markdown_text, markdown_path)
    write_csv(summaries, csv_path)

    print("Aggregated metric files:")
    for metric_file in metric_files:
        print(f"  - {metric_file}")

    print(f"\nMarkdown summary written to: {markdown_path}")
    print(f"CSV summary written to: {csv_path}")


if __name__ == "__main__":
    main()